/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import aleatorio.Calcular;
import aleatorio.Contagiados;
import aleatorio.PorcentajeInf;
import datos.Poblacion;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static jdk.nashorn.internal.runtime.PropertyMap.diff;
/**
 *
 * @author jhonnyapaza
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfazz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pob_input = new javax.swing.JTextField();
        region = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        infectados_input = new javax.swing.JTextField();
        recuperados_input = new javax.swing.JTextField();
        decesos_input = new javax.swing.JTextField();
        activos_input = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        fechaini = new com.toedter.calendar.JDateChooser();
        fechafin = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setLocation(new java.awt.Point(500, 500));
        setMinimumSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(null);

        jButton1.setText("GENERAR DATOS INICIALES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(36, 98, 186, 41);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("POBLACION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(325, 121, 112, 37);

        pob_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pob_inputActionPerformed(evt);
            }
        });
        getContentPane().add(pob_input);
        pob_input.setBounds(449, 123, 131, 37);

        region.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccionar", "Bolivia", "Santa_Cruz", "La_Paz", "Cochabamba", "Sucre", "Tarija", "Beni", "Pando", "Oruro", "Potosi" }));
        region.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionActionPerformed(evt);
            }
        });
        getContentPane().add(region);
        region.setBounds(36, 190, 130, 20);

        jLabel2.setText("Infectados");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(336, 200, 84, 28);

        jLabel3.setText("Recuperados");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 240, 97, 27);

        jLabel4.setText("Decesos");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(336, 279, 74, 32);

        jLabel5.setText("Activos");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(336, 329, 76, 27);

        infectados_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infectados_inputActionPerformed(evt);
            }
        });
        getContentPane().add(infectados_input);
        infectados_input.setBounds(480, 200, 114, 30);
        getContentPane().add(recuperados_input);
        recuperados_input.setBounds(480, 240, 114, 30);
        getContentPane().add(decesos_input);
        decesos_input.setBounds(480, 290, 114, 30);
        getContentPane().add(activos_input);
        activos_input.setBounds(478, 331, 114, 30);

        jButton2.setText("SIMULAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(152, 405, 132, 41);

        jButton3.setText("CANCELAR");
        getContentPane().add(jButton3);
        jButton3.setBounds(434, 405, 134, 41);

        jLabel6.setFont(new java.awt.Font("Marker Felt", 0, 50)); // NOI18N
        jLabel6.setText("COVID-19");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 10, 214, 64);

        fechaini.setToolTipText("fecha");
        fechaini.setDateFormatString("dd MM yyyy");
        getContentPane().add(fechaini);
        fechaini.setBounds(110, 260, 150, 30);

        fechafin.setToolTipText("fecha");
        fechafin.setDateFormatString("dd MM yyyy");
        getContentPane().add(fechafin);
        fechafin.setBounds(110, 300, 150, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("De:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 270, 30, 20);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("A:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 310, 40, 20);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfaces/covid.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 20, 690, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String dpto = region.getSelectedItem().toString();
        Poblacion p = new Poblacion(dpto);
        int a = p.getPoblacion();
        String texto = a + "";
        pob_input.setText(texto);
        int b = p.getDecesos();
        String dec = b +"";
        decesos_input.setText(dec);
        int c = p.getInfectados();
        String inf = c +"";
        infectados_input.setText(inf);
        int d = p.getRecuperados();
        String rec = d +"";
        recuperados_input.setText(rec);
        int e = p.getActivos();
        String act = e +"";
        activos_input.setText(act);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void regionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionActionPerformed
        //TODO add your handling code here:
    }//GEN-LAST:event_regionActionPerformed

    private void infectados_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infectados_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infectados_inputActionPerformed

    private void pob_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pob_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pob_inputActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Date uno = fechaini.getDate();
        Date dos = fechafin.getDate();
        String departamento = region.getSelectedItem().toString();
        long diff,z =0;
        try { 
            Date date1 = uno; 
            Date date2 = dos; 
            diff = date2.getTime() - date1.getTime(); 
            z = TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);
            System.out.println ("Days: " + z); 
        } catch (Exception e) { 
        e.printStackTrace(); 
        } 
        Ventana simular = new Ventana(z, departamento);
        simular.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField activos_input;
    private javax.swing.JTextField decesos_input;
    private com.toedter.calendar.JDateChooser fechafin;
    private com.toedter.calendar.JDateChooser fechaini;
    private javax.swing.JTextField infectados_input;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField pob_input;
    private javax.swing.JTextField recuperados_input;
    private javax.swing.JComboBox<String> region;
    // End of variables declaration//GEN-END:variables
}
