/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import aleatorio.SimulacionPeriodica;
import datos.Poblacion;
import graficador.Graficador;

/**
 *
 * @author jhonnyapaza
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public static int dias;
    public static String region;
    public Ventana(long d, String r) {
        initComponents();
        dias = (int) d;
        region = r;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pob_input = new javax.swing.JTextField();
        infectados_input = new javax.swing.JTextField();
        recuperados_input = new javax.swing.JTextField();
        decesos_input = new javax.swing.JTextField();
        activos_input = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jButton1.setText("MOSTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 10, 123, 30);

        jLabel1.setFont(new java.awt.Font("Kailasa", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cantidad de Poblacion");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 60, 165, 40);

        jLabel2.setFont(new java.awt.Font("Kailasa", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Infectados");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 110, 77, 22);

        jLabel3.setFont(new java.awt.Font("Kailasa", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 255));
        jLabel3.setText("Recuperados");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 150, 95, 28);

        jLabel4.setFont(new java.awt.Font("Kailasa", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 51));
        jLabel4.setText("Decesos");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 190, 66, 26);

        jLabel5.setFont(new java.awt.Font("Kailasa", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ACTIVOS TOTAL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 270, 126, 29);
        getContentPane().add(pob_input);
        pob_input.setBounds(210, 70, 142, 30);
        getContentPane().add(infectados_input);
        infectados_input.setBounds(210, 110, 142, 30);
        getContentPane().add(recuperados_input);
        recuperados_input.setBounds(210, 150, 142, 30);
        getContentPane().add(decesos_input);
        decesos_input.setBounds(210, 190, 142, 30);
        getContentPane().add(activos_input);
        activos_input.setBounds(210, 270, 142, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfaces/Q4zfmEQ.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 690, 380);

        jButton2.setText("Graficar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 390, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SimulacionPeriodica sp = new SimulacionPeriodica(region);
        Poblacion p = new Poblacion(region);
        int inf = sp.nuevosInfectados(dias);
        int rec = sp.nuevosRecuperados(dias);
        int dec=sp.nuevosFallecidos(dias);
        int a = inf - rec - dec;
        String act = a+"";
        infectados_input.setText(inf+"");
        recuperados_input.setText(rec+"");
        decesos_input.setText(dec+"");
        activos_input.setText(act);
        pob_input.setText(p.getPoblacion()+"");
        //Graficador graficar = new Graficador(dias,region );
        //graficar.setVisible(true);
        //dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Graficador graficar = new Graficador(dias,region );
        graficar.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana(dias,region).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField activos_input;
    private javax.swing.JTextField decesos_input;
    private javax.swing.JTextField infectados_input;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField pob_input;
    private javax.swing.JTextField recuperados_input;
    // End of variables declaration//GEN-END:variables
}
